apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: my-container
      image: busybox
      args: [ "tail", "-f", "/dev/null" ]
      volumeMounts:
      - name: my-hostpath-volume
        mountPath: /etc/data # pod의 경로
  volumes:
    - name: my-hostpath-volume
      hostPath:
        path: /tmp # 호스트의 경로