apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - name: nfs-mount-container
      image: busybox
      args: [ "tail", "-f", "/dev/null" ]
      volumeMounts:
      - name: nfs-volume
        mountPath: /mnt           # 포드 컨테이너 내부의 /mnt 디렉터리에 마운트합니다.
  volumes:
  - name : nfs-volume
    nfs:                            # NFS 서버의 볼륨을 포드의 컨테이너에 마운트합니다.
      path: /
      # NFS 볼륨의 마운트는 컨테이너 내부가 아닌 쿠버네티스 노드에서 발생하므로 서비스의 DNS 이름으로는 NFS 서버에 접근 불가능함
      # 즉, 노드에서는 포드의 IP로 통신할 수 있지만, 쿠버네티스의 DNS를 사용할 수는 없음
      # server: {NFS_SERVICE_IP}
      server: 10.110.28.75 # $(kubectl get svc/nfs-service -o jsonpath='{.spec.clusterIP}'